---
# tasks file for sensu

- include: common.yml
  when: (ansible_architecture == "x86_64")

- include: common_ppc.yml
  when: (ansible_architecture == "ppc64le")

- include: server.yml
  when: sensu_install_server

- include: uchiwa.yml
  when: sensu_install_server and sensu_install_uchiwa

- include: client.yml
  when: sensu_install_client
